### check server

http://localhost:8001/

### create wrong url
POST http://localhost:8001/su
content-type: application/json

{
  "url": "https://www.ababcabaababababab.com"
}

### create url
POST http://localhost:8001/su
content-type: application/json

{
  "url": "https://images.pexels.com/photos/699466/pexels-photo-699466.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}

### fetch url
GET http://localhost:8001/su/Km4-Bn3

### create url with alias
POST http://localhost:8001/su
content-type: application/json

{
  "url": "https://www.google.com",
  "alias": "my-google-2"
}

### create url via alias
POST http://localhost:8001/su
content-type: application/json

{
  "url": "http://localhost:8001/su/Km4-Bn3"
}