###
http://localhost:8001/

###
POST http://localhost:8001/su
content-type: application/json

{
  "url": "https://www.google.com"
}

###
GET http://localhost:8001/su/Km4-Bn3

###
POST http://localhost:8001/su
content-type: application/json

{
  "url": "https://www.google.com",
  "alias": "my-google-2"
}

###